# Python: List & matrix #550

In this [python audio](https://drive.google.com/drive/u/0/folders/1h40aLs-jedyJm8F83Ayi_P8ixYNS6hWM) tutorial, we are going to learn about list and matrix in Python. These are the widely used data types in Python. First let us know about list.

## List in Python :

A list is used to store the sequence of various types of data in Python. We can modify its element after it created. That means lists are mutable. We can create python list by putting different comma-separated values between square brackets. The list index starts at 0.

We can Add Elements to a List, using append() or insert() or extend() method. We can remove Elements from the List using remove() or pop() method.

In [4]:
List = []
print("Initial blank List: ")
print(List)
 
# append()
List.append(10)
List.append(20)
print("\nList after Addition of Three elements using append method: ")
print(List)

# insert()
List.insert(3, 30)
print("\nList after Addition of Three elements using insert method: ")
print(List)

# extend()
List.extend([40, 50])
print("\nList after Addition of Three elements using extend method: ")
print(List)

Initial blank List: 
[]

List after Addition of Three elements using append method: 
[10, 20]

List after Addition of Three elements using insert method: 
[10, 20, 30]

List after Addition of Three elements using extend method: 
[10, 20, 30, 40, 50]


In [5]:
List = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Initial List: ")
print(List)
 
# Removing elements from List using Remove() method
List.remove(5)
List.remove(6)
print("\nList after Removal of two elements: ")
print(List)

# Removing elements from List using pop() method
List.pop(2)
print("\nList after popping a specific element: ")
print(List)

Initial List: 
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

List after Removal of two elements: 
[1, 2, 3, 4, 7, 8, 9, 10]

List after popping a specific element: 
[1, 2, 4, 7, 8, 9, 10]


# Matrix in Python :

Now, let's learn about matrices. A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. Python doesn't have a built-in type for matrices. 

We can treat a list of a list as a matrix. Using nested lists as a matrix works for simple computational tasks.

However, there is a better way of working with matrices in Python using NumPy package.

In [1]:
from numpy import * 
a = array([[1,2,3,4,5],[6,7,8,9,10],
   [11,12,13,14,15]])
m = reshape(a,(3,5))
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [2]:
m_c = insert(m,[5],[[10],[20],[30]],1)

print(m_c)

[[ 1  2  3  4  5 10]
 [ 6  7  8  9 10 20]
 [11 12 13 14 15 30]]


In [3]:
m = delete(m,s_[2],1)

print(m)

[[ 1  2  4  5]
 [ 6  7  9 10]
 [11 12 14 15]]
