# **Brief about Feature Scaling and it's Scaling techniques**

Feature scaling is a scaling technique that is used in order to standardize our feature values within a fixed range and it is an essential technique in order to improve the efficiency of our machine learning algorithms and hence the resulting output.

There are various feature scaling techniques but in this tutorial we will be implementing Standardization and Normalization Scaling techniques only.

Normalization is a scaling technique that is used to bring feature values within a range of 0 and 1 given that features values does not follows a gaussian distribution.

Unlike normalization, Standardization is scaling technique where the values are centered around the mean with a unit standard deviation given that features values follows a gaussian distribution.

So, without any further do let's start the practical demo and before starting this demo make sure you download the standardizaton_and_normalization.csv dataset fro DS resources.

In [15]:
# Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Sklearn library 
from sklearn import preprocessing

In [23]:
# Importing Data
   
data_set = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data_for_Missing_Values.csv')
data_set.head()

Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40    1000       Yes

In [18]:
# Slicing features age and salary to handle values with varying magnitude
x = data_set.iloc[:, 1:3].values
print ("\nOriginal data values : \n",  x)


Original data values : 
 [[   44 72000]
 [   27 48000]
 [   30 54000]
 [   38 61000]
 [   40  1000]
 [   35 58000]
 [   78 52000]
 [   48 79000]
 [   50 83000]
 [   37 67000]]


In [19]:
# Applying Normalization
normalization = preprocessing.MinMaxScaler(feature_range =(0, 1))

# After Normalization
after_normalization = normalization.fit_transform(x)
print ("\nAfter Normalization : \n", after_normalization)


After Normalization : 
 [[0.33333333 0.86585366]
 [0.         0.57317073]
 [0.05882353 0.64634146]
 [0.21568627 0.73170732]
 [0.25490196 0.        ]
 [0.15686275 0.69512195]
 [1.         0.62195122]
 [0.41176471 0.95121951]
 [0.45098039 1.        ]
 [0.19607843 0.80487805]]


In [21]:
# Applying Standardization
Standardization = preprocessing.StandardScaler()

# After Standardization
after_Standardization = Standardization.fit_transform(x)
  
print ("\nAfter Standardization : \n", after_Standardization)


After Standardization : 
 [[ 0.09536935  0.66527061]
 [-1.15176827 -0.43586695]
 [-0.93168516 -0.16058256]
 [-0.34479687  0.16058256]
 [-0.1980748  -2.59226136]
 [-0.56487998  0.02294037]
 [ 2.58964459 -0.25234403]
 [ 0.38881349  0.98643574]
 [ 0.53553557  1.16995867]
 [-0.41815791  0.43586695]]


I hope from this example you have understood how to implement standardization and normalization using sklearn library and how it impacts the final outcomes in real world project scenario.