# **DATA SCIENCE PIPELINES** 





*  **Data** is a commodity, but without ways to process it, its value is questionable.A survey in 2016 found that data scientists spend 80% of their time collecting, cleaning, and preparing data for use in machine learning. 

*  **Data Engineering** is a set of operations aimed at creating interfaces and mechanisms for the flow and access of information from the data. It is basically wranlging up with the data and cleaning it for getting insights and using it for future predictions. It is divided into three parts : *Data Wrangling, Data Cleansing, Data Preparation.*

*  For Data transformation and prediction purpose we use Data Science **Pipelines**.

*  **Pipelines** in Data Science are used to take the data from all the data engineering steps and preparing it for the predictions. The outcome of the pipeline is a trained model which can be used to make predictions. The pipeline defines how, what, and where the data is collected. Data pipelining automates data extraction, transformation, validation, and combination, then loads it for further analysis and visualization. 





* We will be using the [**Housing Dataset**](https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv) for this tutorial.


In [1]:
import pandas as pd
import numpy as np
path = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv"
housing = pd.read_csv(path)

In [2]:
housing.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [3]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


*  Creating a new feature **"income_cat"** for stratified splitting of the data into training set and test set.

In [4]:
housing["income_cat"] = pd.cut(housing["median_income"],
                               bins=[0., 1.5, 3.0, 4.5, 6., np.inf],
                               labels=[1, 2, 3, 4, 5])

In [5]:
housing["income_cat"].value_counts()

3    7236
2    6581
4    3639
5    2362
1     822
Name: income_cat, dtype: int64

*  Housing dataset with new feature **"income_cat"**.

In [6]:
housing.head()

longitude  latitude  ...  ocean_proximity  income_cat
0    -122.23     37.88  ...         NEAR BAY           5
1    -122.22     37.86  ...         NEAR BAY           5
2    -122.24     37.85  ...         NEAR BAY           5
3    -122.25     37.85  ...         NEAR BAY           4
4    -122.25     37.85  ...         NEAR BAY           3

[5 rows x 11 columns]

*  Using **StratifiedShuffleSplit** to creat strat_traint_set and strat_test_set.

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits =1, test_size = 0.2, random_state =42)
for train_index , test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.iloc[train_index]
    strat_test_set = housing.iloc[test_index]

In [8]:
strat_test_set.head()

longitude  latitude  ...  ocean_proximity  income_cat
5241     -118.39     34.12  ...        <1H OCEAN           5
10970    -117.86     33.77  ...        <1H OCEAN           4
20351    -119.05     34.21  ...        <1H OCEAN           3
6568     -118.15     34.20  ...           INLAND           3
13285    -117.68     34.07  ...           INLAND           3

[5 rows x 11 columns]

In [9]:
strat_train_set.head()

longitude  latitude  ...  ocean_proximity  income_cat
17606    -121.89     37.29  ...        <1H OCEAN           2
18632    -121.93     37.05  ...        <1H OCEAN           5
14650    -117.20     32.77  ...       NEAR OCEAN           2
3230     -119.61     36.31  ...           INLAND           2
3555     -118.59     34.23  ...        <1H OCEAN           3

[5 rows x 11 columns]

*  Droping the **Labels**(predictions) from the Housing dataset and creating a new dataframe for the Labels.

In [10]:
housing = strat_train_set.drop("median_house_value", axis=1) 
housing_labels = strat_train_set["median_house_value"].copy()

In [11]:
strat_train_set.head()

longitude  latitude  ...  ocean_proximity  income_cat
17606    -121.89     37.29  ...        <1H OCEAN           2
18632    -121.93     37.05  ...        <1H OCEAN           5
14650    -117.20     32.77  ...       NEAR OCEAN           2
3230     -119.61     36.31  ...           INLAND           2
3555     -118.59     34.23  ...        <1H OCEAN           3

[5 rows x 11 columns]

In [12]:
housing.head()

longitude  latitude  ...  ocean_proximity  income_cat
17606    -121.89     37.29  ...        <1H OCEAN           2
18632    -121.93     37.05  ...        <1H OCEAN           5
14650    -117.20     32.77  ...       NEAR OCEAN           2
3230     -119.61     36.31  ...           INLAND           2
3555     -118.59     34.23  ...        <1H OCEAN           3

[5 rows x 10 columns]

*  **SimpleImputer** is used to fill in the missing numerical values with the **Statistical Value**(here,strategy = "median") of the respective feature. 

**Note** : Imputer works only on **numerical columns**. So, we need to separte the numerical columns from the categorical columns.

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

In [14]:
housing_num = housing.drop("ocean_proximity",axis=1)
imputer.fit(housing_num)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

*  These are the statiscal values of each numerical column.

In [15]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409,    3.    ])

In [16]:
X= imputer.transform(housing_num)

In [17]:
housing_tr = pd.DataFrame(X,columns=housing_num.columns,index=housing_num.index)

In [18]:
housing_tr.head()

longitude  latitude  ...  median_income  income_cat
17606    -121.89     37.29  ...         2.7042         2.0
18632    -121.93     37.05  ...         6.4214         5.0
14650    -117.20     32.77  ...         2.8621         2.0
3230     -119.61     36.31  ...         1.8839         2.0
3555     -118.59     34.23  ...         3.0347         3.0

[5 rows x 9 columns]

In [19]:
housing_cat = housing[["ocean_proximity"]] #Categorical Attribute
housing_cat.head(10)

ocean_proximity
17606       <1H OCEAN
18632       <1H OCEAN
14650      NEAR OCEAN
3230           INLAND
3555        <1H OCEAN
19480          INLAND
8879        <1H OCEAN
13685          INLAND
4937        <1H OCEAN
4861        <1H OCEAN

*  Using **OneHotEncoder** to handle the categorical attributes and convert them to numerical data in the form of sparse matrix as Machine Learning algorithms prefer to work with numbers.

In [20]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot


<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [21]:
housing_cat_1hot.toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

*  As we have seen there are many data transformation steps that need to be executed in a particular sequence so as to prepare the data for the model.
One way to help such sequence of transformation is to use **Pipeline**.

*  **Pipeline** is used to handle all the data transformation steps in a sequence and to prepare a trained model for the predictions.

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
                ('std_scaler', StandardScaler()),
    ])

housing_num_tr = num_pipeline.fit_transform(housing_num)

In [23]:
housing_num_tr

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.42069842,
        -0.61493744, -0.95445595],
       [-1.17602483,  0.6596948 , -1.1653172 , ..., -1.02222705,
         1.33645936,  1.89030518],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.0933178 ,
        -0.5320456 , -0.95445595],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.71315642,
        -0.3167053 , -0.00620224],
       [ 0.78221312, -0.85106801,  0.18664186, ..., -0.37545069,
         0.09812139, -0.00620224],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.3777909 ,
        -0.15779865, -0.00620224]])

*  We can work on numerical and categorical attributes simultaneously by using a single transformer(Pipeline) which will apply appropriate transformation to each column. And this can be applied using **ColumnTransformer**.

In [24]:
from sklearn.compose import ColumnTransformer
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]
full_pipeline = ColumnTransformer ([ ("num", num_pipeline,num_attribs),
                                     ("cat",OneHotEncoder(),cat_attribs)])
housing_prepared = full_pipeline.fit_transform(housing)

*  Using **LinearRegression** model for predictions

In [25]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [26]:
lin_reg.fit(housing_prepared, housing_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
lin_reg.predict(housing_prepared)

array([205841.96139906, 329060.05217695, 205219.96047357, ...,
       100690.6084635 , 215934.8748381 , 278815.04829906])

# **Conclusion**

*  In this notebook we imported housing dataset and used data engineering steps to extract, transform and clean the data and then we used pipelines to accomodate all the data transformation steps into one code block rather than just transforming the data in every transformer that we created. Here, we can include the model in the pipeline as well and then directly fit the pipeline to the data imported from the source for the training of the model based on the Machine learning algorithms. We can also include model validation and fine tuning model steps in the pipeline.

*  Working with pipelines means incorporating the steps of obtaining and cleaning the data, exploring data with visualizations, modeling data with different machine learning algorithms, interpreting data by evaluation, and updating the model.
*  Pipelines provide easier access to insights, as raw data is quickly and easily adjusted, analyzed, and modeled based on machine learning algorithms.